repos:
-   repo: https://github.com/igrr/astyle_py.git
    rev: 689550dafa9bf64075efc1a683f6fffebbcaaf00
    hooks:
    -   id: astyle_py
        args: ['--style=otbs', '--attach-namespaces', '--attach-classes', '--indent=spaces=4', '--convert-tabs', '--align-pointer=name', '--align-reference=name', '--keep-one-line-statements', '--pad-header', '--pad-oper']
